// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type ErrorCode struct {
	Err                  int32    `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorCode) Reset()         { *m = ErrorCode{} }
func (m *ErrorCode) String() string { return proto.CompactTextString(m) }
func (*ErrorCode) ProtoMessage()    {}
func (*ErrorCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *ErrorCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorCode.Unmarshal(m, b)
}
func (m *ErrorCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorCode.Marshal(b, m, deterministic)
}
func (m *ErrorCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorCode.Merge(m, src)
}
func (m *ErrorCode) XXX_Size() int {
	return xxx_messageInfo_ErrorCode.Size(m)
}
func (m *ErrorCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorCode.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorCode proto.InternalMessageInfo

func (m *ErrorCode) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *ErrorCode) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Service struct {
	ID                   *ID      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetID() *ID {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *Service) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type SkillCategory struct {
	ID                   *ID      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillCategory) Reset()         { *m = SkillCategory{} }
func (m *SkillCategory) String() string { return proto.CompactTextString(m) }
func (*SkillCategory) ProtoMessage()    {}
func (*SkillCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *SkillCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillCategory.Unmarshal(m, b)
}
func (m *SkillCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillCategory.Marshal(b, m, deterministic)
}
func (m *SkillCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillCategory.Merge(m, src)
}
func (m *SkillCategory) XXX_Size() int {
	return xxx_messageInfo_SkillCategory.Size(m)
}
func (m *SkillCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillCategory.DiscardUnknown(m)
}

var xxx_messageInfo_SkillCategory proto.InternalMessageInfo

func (m *SkillCategory) GetID() *ID {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *SkillCategory) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type Skill struct {
	ID                   *ID            `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Category             *SkillCategory `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Skill                string         `protobuf:"bytes,3,opt,name=skill,proto3" json:"skill,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Skill) Reset()         { *m = Skill{} }
func (m *Skill) String() string { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()    {}
func (*Skill) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *Skill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skill.Unmarshal(m, b)
}
func (m *Skill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skill.Marshal(b, m, deterministic)
}
func (m *Skill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skill.Merge(m, src)
}
func (m *Skill) XXX_Size() int {
	return xxx_messageInfo_Skill.Size(m)
}
func (m *Skill) XXX_DiscardUnknown() {
	xxx_messageInfo_Skill.DiscardUnknown(m)
}

var xxx_messageInfo_Skill proto.InternalMessageInfo

func (m *Skill) GetID() *ID {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *Skill) GetCategory() *SkillCategory {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Skill) GetSkill() string {
	if m != nil {
		return m.Skill
	}
	return ""
}

type CreateJob struct {
	EUID                 *ID            `protobuf:"bytes,1,opt,name=EUID,proto3" json:"EUID,omitempty"`
	Service              *Service       `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Category             *SkillCategory `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Wage                 float32        `protobuf:"fixed32,4,opt,name=wage,proto3" json:"wage,omitempty"`
	Places               int32          `protobuf:"varint,5,opt,name=places,proto3" json:"places,omitempty"`
	Title                string         `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Exp                  string         `protobuf:"bytes,7,opt,name=exp,proto3" json:"exp,omitempty"`
	Description          string         `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateJob) Reset()         { *m = CreateJob{} }
func (m *CreateJob) String() string { return proto.CompactTextString(m) }
func (*CreateJob) ProtoMessage()    {}
func (*CreateJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *CreateJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJob.Unmarshal(m, b)
}
func (m *CreateJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJob.Marshal(b, m, deterministic)
}
func (m *CreateJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJob.Merge(m, src)
}
func (m *CreateJob) XXX_Size() int {
	return xxx_messageInfo_CreateJob.Size(m)
}
func (m *CreateJob) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJob.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJob proto.InternalMessageInfo

func (m *CreateJob) GetEUID() *ID {
	if m != nil {
		return m.EUID
	}
	return nil
}

func (m *CreateJob) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *CreateJob) GetCategory() *SkillCategory {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *CreateJob) GetWage() float32 {
	if m != nil {
		return m.Wage
	}
	return 0
}

func (m *CreateJob) GetPlaces() int32 {
	if m != nil {
		return m.Places
	}
	return 0
}

func (m *CreateJob) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateJob) GetExp() string {
	if m != nil {
		return m.Exp
	}
	return ""
}

func (m *CreateJob) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Job struct {
	EUID                 *ID            `protobuf:"bytes,1,opt,name=EUID,proto3" json:"EUID,omitempty"`
	Service              *Service       `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Category             *SkillCategory `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Wage                 float32        `protobuf:"fixed32,4,opt,name=wage,proto3" json:"wage,omitempty"`
	Places               int32          `protobuf:"varint,5,opt,name=places,proto3" json:"places,omitempty"`
	Title                string         `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Exp                  string         `protobuf:"bytes,7,opt,name=exp,proto3" json:"exp,omitempty"`
	Description          string         `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	PostTime             string         `protobuf:"bytes,9,opt,name=postTime,proto3" json:"postTime,omitempty"`
	NrOfCandidates       int32          `protobuf:"varint,10,opt,name=nrOfCandidates,proto3" json:"nrOfCandidates,omitempty"`
	EmployerRating       float32        `protobuf:"fixed32,11,opt,name=employerRating,proto3" json:"employerRating,omitempty"`
	MoneySpent           float32        `protobuf:"fixed32,12,opt,name=moneySpent,proto3" json:"moneySpent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetEUID() *ID {
	if m != nil {
		return m.EUID
	}
	return nil
}

func (m *Job) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Job) GetCategory() *SkillCategory {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Job) GetWage() float32 {
	if m != nil {
		return m.Wage
	}
	return 0
}

func (m *Job) GetPlaces() int32 {
	if m != nil {
		return m.Places
	}
	return 0
}

func (m *Job) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Job) GetExp() string {
	if m != nil {
		return m.Exp
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetPostTime() string {
	if m != nil {
		return m.PostTime
	}
	return ""
}

func (m *Job) GetNrOfCandidates() int32 {
	if m != nil {
		return m.NrOfCandidates
	}
	return 0
}

func (m *Job) GetEmployerRating() float32 {
	if m != nil {
		return m.EmployerRating
	}
	return 0
}

func (m *Job) GetMoneySpent() float32 {
	if m != nil {
		return m.MoneySpent
	}
	return 0
}

type JobApplication struct {
	JID                  *ID      `protobuf:"bytes,1,opt,name=JID,proto3" json:"JID,omitempty"`
	FUID                 *ID      `protobuf:"bytes,2,opt,name=FUID,proto3" json:"FUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobApplication) Reset()         { *m = JobApplication{} }
func (m *JobApplication) String() string { return proto.CompactTextString(m) }
func (*JobApplication) ProtoMessage()    {}
func (*JobApplication) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *JobApplication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobApplication.Unmarshal(m, b)
}
func (m *JobApplication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobApplication.Marshal(b, m, deterministic)
}
func (m *JobApplication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobApplication.Merge(m, src)
}
func (m *JobApplication) XXX_Size() int {
	return xxx_messageInfo_JobApplication.Size(m)
}
func (m *JobApplication) XXX_DiscardUnknown() {
	xxx_messageInfo_JobApplication.DiscardUnknown(m)
}

var xxx_messageInfo_JobApplication proto.InternalMessageInfo

func (m *JobApplication) GetJID() *ID {
	if m != nil {
		return m.JID
	}
	return nil
}

func (m *JobApplication) GetFUID() *ID {
	if m != nil {
		return m.FUID
	}
	return nil
}

type JobSelection struct {
	JID                  *ID      `protobuf:"bytes,1,opt,name=JID,proto3" json:"JID,omitempty"`
	FUID                 *ID      `protobuf:"bytes,2,opt,name=FUID,proto3" json:"FUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobSelection) Reset()         { *m = JobSelection{} }
func (m *JobSelection) String() string { return proto.CompactTextString(m) }
func (*JobSelection) ProtoMessage()    {}
func (*JobSelection) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *JobSelection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobSelection.Unmarshal(m, b)
}
func (m *JobSelection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobSelection.Marshal(b, m, deterministic)
}
func (m *JobSelection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobSelection.Merge(m, src)
}
func (m *JobSelection) XXX_Size() int {
	return xxx_messageInfo_JobSelection.Size(m)
}
func (m *JobSelection) XXX_DiscardUnknown() {
	xxx_messageInfo_JobSelection.DiscardUnknown(m)
}

var xxx_messageInfo_JobSelection proto.InternalMessageInfo

func (m *JobSelection) GetJID() *ID {
	if m != nil {
		return m.JID
	}
	return nil
}

func (m *JobSelection) GetFUID() *ID {
	if m != nil {
		return m.FUID
	}
	return nil
}

type EmployerProfile struct {
	EUID                 *ID      `protobuf:"bytes,1,opt,name=EUID,proto3" json:"EUID,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty"`
	Rating               float32  `protobuf:"fixed32,5,opt,name=rating,proto3" json:"rating,omitempty"`
	JobsPosted           int32    `protobuf:"varint,6,opt,name=jobsPosted,proto3" json:"jobsPosted,omitempty"`
	MoneySpent           float32  `protobuf:"fixed32,7,opt,name=moneySpent,proto3" json:"moneySpent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployerProfile) Reset()         { *m = EmployerProfile{} }
func (m *EmployerProfile) String() string { return proto.CompactTextString(m) }
func (*EmployerProfile) ProtoMessage()    {}
func (*EmployerProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *EmployerProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployerProfile.Unmarshal(m, b)
}
func (m *EmployerProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployerProfile.Marshal(b, m, deterministic)
}
func (m *EmployerProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployerProfile.Merge(m, src)
}
func (m *EmployerProfile) XXX_Size() int {
	return xxx_messageInfo_EmployerProfile.Size(m)
}
func (m *EmployerProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployerProfile.DiscardUnknown(m)
}

var xxx_messageInfo_EmployerProfile proto.InternalMessageInfo

func (m *EmployerProfile) GetEUID() *ID {
	if m != nil {
		return m.EUID
	}
	return nil
}

func (m *EmployerProfile) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *EmployerProfile) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *EmployerProfile) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *EmployerProfile) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *EmployerProfile) GetJobsPosted() int32 {
	if m != nil {
		return m.JobsPosted
	}
	return 0
}

func (m *EmployerProfile) GetMoneySpent() float32 {
	if m != nil {
		return m.MoneySpent
	}
	return 0
}

type FreelancerProfile struct {
	FUID                 *ID      `protobuf:"bytes,1,opt,name=FUID,proto3" json:"FUID,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty"`
	Rating               float32  `protobuf:"fixed32,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Balance              float32  `protobuf:"fixed32,6,opt,name=balance,proto3" json:"balance,omitempty"`
	Description          string   `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Photo                string   `protobuf:"bytes,8,opt,name=photo,proto3" json:"photo,omitempty"`
	MainSkill            *Skill   `protobuf:"bytes,9,opt,name=mainSkill,proto3" json:"mainSkill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FreelancerProfile) Reset()         { *m = FreelancerProfile{} }
func (m *FreelancerProfile) String() string { return proto.CompactTextString(m) }
func (*FreelancerProfile) ProtoMessage()    {}
func (*FreelancerProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *FreelancerProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FreelancerProfile.Unmarshal(m, b)
}
func (m *FreelancerProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FreelancerProfile.Marshal(b, m, deterministic)
}
func (m *FreelancerProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreelancerProfile.Merge(m, src)
}
func (m *FreelancerProfile) XXX_Size() int {
	return xxx_messageInfo_FreelancerProfile.Size(m)
}
func (m *FreelancerProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_FreelancerProfile.DiscardUnknown(m)
}

var xxx_messageInfo_FreelancerProfile proto.InternalMessageInfo

func (m *FreelancerProfile) GetFUID() *ID {
	if m != nil {
		return m.FUID
	}
	return nil
}

func (m *FreelancerProfile) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *FreelancerProfile) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *FreelancerProfile) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *FreelancerProfile) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *FreelancerProfile) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *FreelancerProfile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FreelancerProfile) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *FreelancerProfile) GetMainSkill() *Skill {
	if m != nil {
		return m.MainSkill
	}
	return nil
}

func init() {
	proto.RegisterType((*Void)(nil), "api.Void")
	proto.RegisterType((*ErrorCode)(nil), "api.ErrorCode")
	proto.RegisterType((*ID)(nil), "api.ID")
	proto.RegisterType((*Service)(nil), "api.Service")
	proto.RegisterType((*SkillCategory)(nil), "api.SkillCategory")
	proto.RegisterType((*Skill)(nil), "api.Skill")
	proto.RegisterType((*CreateJob)(nil), "api.CreateJob")
	proto.RegisterType((*Job)(nil), "api.Job")
	proto.RegisterType((*JobApplication)(nil), "api.JobApplication")
	proto.RegisterType((*JobSelection)(nil), "api.JobSelection")
	proto.RegisterType((*EmployerProfile)(nil), "api.EmployerProfile")
	proto.RegisterType((*FreelancerProfile)(nil), "api.FreelancerProfile")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 828 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x56, 0xdd, 0xae, 0xdb, 0x44,
	0x10, 0x96, 0x9d, 0x1f, 0xc7, 0x93, 0x34, 0xa5, 0xdb, 0xf4, 0x60, 0x02, 0xaa, 0x22, 0x03, 0x47,
	0x91, 0x90, 0x0e, 0xc1, 0xbd, 0x40, 0xa8, 0x48, 0xa8, 0xca, 0x5f, 0x4f, 0x2e, 0xa0, 0x72, 0x80,
	0x7b, 0xc7, 0x9e, 0xa4, 0x0b, 0x8e, 0xd7, 0xda, 0x5d, 0x41, 0xf3, 0x1e, 0x3c, 0x09, 0x0f, 0xc3,
	0xa3, 0xf4, 0x8a, 0x0b, 0xb4, 0x6b, 0xc7, 0x71, 0xec, 0x04, 0x2a, 0x21, 0x71, 0xc3, 0x4d, 0xe4,
	0xf9, 0xe6, 0xf7, 0x9b, 0x19, 0x8f, 0x03, 0x76, 0x90, 0xd2, 0xbb, 0x94, 0x33, 0xc9, 0x48, 0x23,
	0x48, 0xa9, 0xdb, 0x86, 0xe6, 0x8f, 0x8c, 0x46, 0xee, 0xe7, 0x60, 0xcf, 0x39, 0x67, 0x7c, 0xca,
	0x22, 0x24, 0xef, 0x41, 0x03, 0x39, 0x77, 0x8c, 0x91, 0x31, 0x6e, 0xf9, 0xea, 0x51, 0x21, 0x7b,
	0xb1, 0x73, 0xcc, 0x91, 0x31, 0xb6, 0x7d, 0xf5, 0xe8, 0x0e, 0xc0, 0xbc, 0x9f, 0x91, 0xbe, 0xfa,
	0xd5, 0x86, 0xb6, 0x6f, 0xde, 0xcf, 0xdc, 0xaf, 0xc1, 0x5a, 0x23, 0xff, 0x85, 0x86, 0x48, 0xde,
	0x2f, 0x54, 0x5d, 0xcf, 0xba, 0x53, 0x69, 0xef, 0x67, 0xca, 0x86, 0x38, 0x60, 0x89, 0xcc, 0x26,
	0x8f, 0x77, 0x14, 0xdd, 0x19, 0x3c, 0x58, 0xff, 0x4c, 0xe3, 0x78, 0x1a, 0x48, 0xdc, 0x31, 0x7e,
	0xb8, 0x1e, 0x63, 0x08, 0x9d, 0x30, 0x37, 0xca, 0x83, 0x14, 0xb2, 0xbb, 0x85, 0x96, 0x8e, 0x72,
	0xdd, 0xfb, 0xae, 0xe2, 0xdd, 0xf5, 0x88, 0x56, 0x9f, 0x25, 0x3f, 0x45, 0x24, 0x03, 0x68, 0x09,
	0xa5, 0x72, 0x1a, 0x3a, 0x55, 0x26, 0xb8, 0x6f, 0x0d, 0xb0, 0xa7, 0x1c, 0x03, 0x89, 0x2b, 0xb6,
	0x21, 0x1f, 0x42, 0x73, 0xfe, 0x43, 0x3d, 0x9d, 0x06, 0xc9, 0xed, 0x39, 0xe5, 0xae, 0xd7, 0xcb,
	0xf2, 0x65, 0x58, 0xd1, 0x80, 0xb3, 0xc2, 0x1a, 0xef, 0x50, 0x18, 0x81, 0xe6, 0xaf, 0xc1, 0x0e,
	0x9d, 0xe6, 0xc8, 0x18, 0x9b, 0xbe, 0x7e, 0x26, 0x37, 0xd0, 0x4e, 0xe3, 0x20, 0x44, 0xe1, 0xb4,
	0xf4, 0xfc, 0x72, 0x49, 0x91, 0x90, 0x54, 0xc6, 0xe8, 0xb4, 0x33, 0x12, 0x5a, 0xd0, 0xa3, 0x7e,
	0x93, 0x3a, 0x56, 0x36, 0x58, 0x7c, 0x93, 0x92, 0x11, 0x74, 0x23, 0x14, 0x21, 0xa7, 0xa9, 0xa4,
	0x2c, 0x71, 0x3a, 0x5a, 0x53, 0x86, 0xdc, 0x3f, 0x4d, 0x68, 0xfc, 0xbf, 0x28, 0xab, 0x7d, 0x4b,
	0x99, 0x90, 0xdf, 0xd3, 0x3d, 0x3a, 0x76, 0xb6, 0x6f, 0x47, 0x99, 0xdc, 0x42, 0x3f, 0xe1, 0xdf,
	0x6d, 0xa7, 0x41, 0x12, 0xd1, 0x28, 0x90, 0x28, 0x1c, 0xd0, 0x55, 0x54, 0x50, 0x65, 0x87, 0xfb,
	0x34, 0x66, 0x07, 0xe4, 0x7e, 0x20, 0x69, 0xb2, 0x73, 0xba, 0x9a, 0x43, 0x05, 0x25, 0x4f, 0x01,
	0xf6, 0x2c, 0xc1, 0xc3, 0x3a, 0xc5, 0x44, 0x3a, 0x3d, 0x6d, 0x53, 0x42, 0xdc, 0x97, 0xd0, 0x5f,
	0xb1, 0xcd, 0x8b, 0x34, 0x8d, 0x69, 0x18, 0xe8, 0xea, 0x3e, 0x80, 0xc6, 0xaa, 0x3e, 0x07, 0x85,
	0xa9, 0x19, 0x2d, 0xd4, 0x8c, 0xcc, 0xca, 0x8c, 0x14, 0xe8, 0x2e, 0xa0, 0xb7, 0x62, 0x9b, 0x35,
	0xc6, 0x18, 0xfe, 0xab, 0x38, 0x7f, 0x18, 0xf0, 0x70, 0x9e, 0x93, 0x78, 0xc5, 0xd9, 0x96, 0xc6,
	0xf8, 0xf7, 0xcb, 0x31, 0x80, 0x56, 0xfa, 0x9a, 0x25, 0xc7, 0x03, 0x90, 0x09, 0xaa, 0xc9, 0x71,
	0x20, 0xe4, 0xb7, 0xc1, 0x1e, 0xf3, 0x37, 0xad, 0x90, 0xc9, 0x47, 0x60, 0x6f, 0x29, 0xcf, 0x95,
	0x4d, 0xad, 0x3c, 0x01, 0x6a, 0x01, 0x78, 0xd6, 0xd2, 0x96, 0x6e, 0x57, 0x2e, 0xa9, 0x56, 0xfe,
	0xc4, 0x36, 0xe2, 0x15, 0x13, 0x12, 0x23, 0xbd, 0x05, 0x2d, 0xbf, 0x84, 0x54, 0x5a, 0x6d, 0xd5,
	0x5a, 0xfd, 0x9b, 0x09, 0x8f, 0x16, 0x1c, 0x31, 0x0e, 0x92, 0xf0, 0x8c, 0xda, 0xe2, 0x12, 0xb5,
	0xc5, 0x7f, 0x49, 0xcd, 0x01, 0x6b, 0x13, 0xe8, 0xba, 0x34, 0x2f, 0xd3, 0x3f, 0x8a, 0xd5, 0x6d,
	0xb6, 0xea, 0xdb, 0x9c, 0xd5, 0x28, 0x59, 0xbe, 0xe9, 0x99, 0x40, 0xc6, 0x60, 0xef, 0x03, 0x9a,
	0xe8, 0x17, 0x4f, 0x2f, 0x79, 0xd7, 0x83, 0xd3, 0xab, 0xe8, 0x9f, 0x94, 0xde, 0x5b, 0x03, 0x3a,
	0x79, 0x33, 0x04, 0x79, 0x0e, 0x8f, 0xe7, 0x11, 0x95, 0xd5, 0xf9, 0x0f, 0xb4, 0x6b, 0x05, 0x1d,
	0xf6, 0x33, 0xb4, 0xf8, 0xd2, 0x7c, 0x03, 0x4f, 0x94, 0x73, 0xbd, 0xc7, 0x37, 0xda, 0xb0, 0x86,
	0xd7, 0x02, 0x3c, 0x03, 0xb2, 0xc4, 0x5a, 0xf2, 0xe3, 0x4c, 0x86, 0x17, 0xab, 0x20, 0x5f, 0xc2,
	0x60, 0x89, 0x17, 0x92, 0x16, 0x6e, 0x57, 0xb2, 0x7b, 0xbf, 0x37, 0xa1, 0xb9, 0x62, 0x1b, 0x41,
	0x3e, 0x83, 0xfe, 0x12, 0xe5, 0x8b, 0x38, 0xce, 0xef, 0x99, 0x20, 0xb6, 0x76, 0x51, 0xdf, 0xd2,
	0xe1, 0xd9, 0xa5, 0x9b, 0x18, 0xe4, 0x2b, 0x78, 0x92, 0x1b, 0x97, 0x6e, 0x1a, 0x45, 0x41, 0x4a,
	0xed, 0x1d, 0x5e, 0xb8, 0x7a, 0x13, 0x83, 0x4c, 0xa0, 0x57, 0x72, 0x15, 0xe4, 0x82, 0xd5, 0xb0,
	0x14, 0x65, 0x62, 0x90, 0x8f, 0xc1, 0x52, 0xcb, 0xad, 0xee, 0x73, 0xd6, 0xab, 0xe2, 0x13, 0x35,
	0xec, 0x68, 0x59, 0x69, 0x9e, 0x82, 0xb5, 0x44, 0xa9, 0x99, 0x14, 0x9c, 0x0b, 0xed, 0xc4, 0x20,
	0x1e, 0x74, 0xd5, 0x7d, 0x39, 0x2c, 0x18, 0x57, 0xe6, 0x8f, 0x8f, 0xaa, 0xd2, 0xd1, 0xa9, 0x4d,
	0xc2, 0x83, 0x07, 0xaa, 0xd4, 0xcc, 0x22, 0x91, 0xe2, 0x1f, 0xbb, 0x39, 0x31, 0xc8, 0x17, 0xd0,
	0xcb, 0xae, 0x4f, 0x9e, 0xe8, 0xd1, 0x31, 0x51, 0x71, 0x93, 0x6a, 0x69, 0x9e, 0xc3, 0x8d, 0x4a,
	0x13, 0x86, 0x98, 0x4a, 0x8c, 0x4e, 0x41, 0xdf, 0x29, 0xdf, 0x2d, 0x3c, 0x2c, 0x39, 0x5f, 0xe7,
	0xff, 0xa9, 0x1e, 0xef, 0x4b, 0x2a, 0x24, 0xe3, 0x87, 0xeb, 0x66, 0x9f, 0x80, 0xbd, 0xa0, 0x09,
	0x15, 0xaf, 0x55, 0xed, 0x85, 0x45, 0xa5, 0xe2, 0x4d, 0x5b, 0xff, 0xdd, 0x7a, 0xf6, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x3c, 0x6b, 0xd4, 0x16, 0x7b, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProfilesClient is the client API for Profiles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfilesClient interface {
	EditEmployerProfile(ctx context.Context, in *EmployerProfile, opts ...grpc.CallOption) (*ErrorCode, error)
	EditFreelancerProfile(ctx context.Context, in *FreelancerProfile, opts ...grpc.CallOption) (*ErrorCode, error)
	GetEmployerProfile(ctx context.Context, in *ID, opts ...grpc.CallOption) (*EmployerProfile, error)
	GetFreelancerProfile(ctx context.Context, in *ID, opts ...grpc.CallOption) (*FreelancerProfile, error)
}

type profilesClient struct {
	cc grpc.ClientConnInterface
}

func NewProfilesClient(cc grpc.ClientConnInterface) ProfilesClient {
	return &profilesClient{cc}
}

func (c *profilesClient) EditEmployerProfile(ctx context.Context, in *EmployerProfile, opts ...grpc.CallOption) (*ErrorCode, error) {
	out := new(ErrorCode)
	err := c.cc.Invoke(ctx, "/api.Profiles/EditEmployerProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) EditFreelancerProfile(ctx context.Context, in *FreelancerProfile, opts ...grpc.CallOption) (*ErrorCode, error) {
	out := new(ErrorCode)
	err := c.cc.Invoke(ctx, "/api.Profiles/EditFreelancerProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) GetEmployerProfile(ctx context.Context, in *ID, opts ...grpc.CallOption) (*EmployerProfile, error) {
	out := new(EmployerProfile)
	err := c.cc.Invoke(ctx, "/api.Profiles/GetEmployerProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) GetFreelancerProfile(ctx context.Context, in *ID, opts ...grpc.CallOption) (*FreelancerProfile, error) {
	out := new(FreelancerProfile)
	err := c.cc.Invoke(ctx, "/api.Profiles/GetFreelancerProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfilesServer is the server API for Profiles service.
type ProfilesServer interface {
	EditEmployerProfile(context.Context, *EmployerProfile) (*ErrorCode, error)
	EditFreelancerProfile(context.Context, *FreelancerProfile) (*ErrorCode, error)
	GetEmployerProfile(context.Context, *ID) (*EmployerProfile, error)
	GetFreelancerProfile(context.Context, *ID) (*FreelancerProfile, error)
}

// UnimplementedProfilesServer can be embedded to have forward compatible implementations.
type UnimplementedProfilesServer struct {
}

func (*UnimplementedProfilesServer) EditEmployerProfile(ctx context.Context, req *EmployerProfile) (*ErrorCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditEmployerProfile not implemented")
}
func (*UnimplementedProfilesServer) EditFreelancerProfile(ctx context.Context, req *FreelancerProfile) (*ErrorCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditFreelancerProfile not implemented")
}
func (*UnimplementedProfilesServer) GetEmployerProfile(ctx context.Context, req *ID) (*EmployerProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployerProfile not implemented")
}
func (*UnimplementedProfilesServer) GetFreelancerProfile(ctx context.Context, req *ID) (*FreelancerProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFreelancerProfile not implemented")
}

func RegisterProfilesServer(s *grpc.Server, srv ProfilesServer) {
	s.RegisterService(&_Profiles_serviceDesc, srv)
}

func _Profiles_EditEmployerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployerProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).EditEmployerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Profiles/EditEmployerProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).EditEmployerProfile(ctx, req.(*EmployerProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_EditFreelancerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreelancerProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).EditFreelancerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Profiles/EditFreelancerProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).EditFreelancerProfile(ctx, req.(*FreelancerProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_GetEmployerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).GetEmployerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Profiles/GetEmployerProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).GetEmployerProfile(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_GetFreelancerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).GetFreelancerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Profiles/GetFreelancerProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).GetFreelancerProfile(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profiles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Profiles",
	HandlerType: (*ProfilesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EditEmployerProfile",
			Handler:    _Profiles_EditEmployerProfile_Handler,
		},
		{
			MethodName: "EditFreelancerProfile",
			Handler:    _Profiles_EditFreelancerProfile_Handler,
		},
		{
			MethodName: "GetEmployerProfile",
			Handler:    _Profiles_GetEmployerProfile_Handler,
		},
		{
			MethodName: "GetFreelancerProfile",
			Handler:    _Profiles_GetFreelancerProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// JobsClient is the client API for Jobs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobsClient interface {
	GetAllServices(ctx context.Context, in *Void, opts ...grpc.CallOption) (Jobs_GetAllServicesClient, error)
	GetAllSkillCategories(ctx context.Context, in *Skill, opts ...grpc.CallOption) (Jobs_GetAllSkillCategoriesClient, error)
	GetAllSkills(ctx context.Context, in *SkillCategory, opts ...grpc.CallOption) (Jobs_GetAllSkillsClient, error)
	PostJob(ctx context.Context, in *CreateJob, opts ...grpc.CallOption) (*Job, error)
	GetJobs(ctx context.Context, in *ID, opts ...grpc.CallOption) (Jobs_GetJobsClient, error)
	ApplyForJob(ctx context.Context, in *JobApplication, opts ...grpc.CallOption) (*ErrorCode, error)
	GetApplicants(ctx context.Context, in *ID, opts ...grpc.CallOption) (Jobs_GetApplicantsClient, error)
	SelectForJob(ctx context.Context, in *JobSelection, opts ...grpc.CallOption) (*ErrorCode, error)
	GetAcceptedFreelancers(ctx context.Context, in *ID, opts ...grpc.CallOption) (Jobs_GetAcceptedFreelancersClient, error)
	GetAcceptedJobs(ctx context.Context, in *ID, opts ...grpc.CallOption) (Jobs_GetAcceptedJobsClient, error)
	GetHistoryJobs(ctx context.Context, in *ID, opts ...grpc.CallOption) (Jobs_GetHistoryJobsClient, error)
	FinishJob(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ErrorCode, error)
}

type jobsClient struct {
	cc grpc.ClientConnInterface
}

func NewJobsClient(cc grpc.ClientConnInterface) JobsClient {
	return &jobsClient{cc}
}

func (c *jobsClient) GetAllServices(ctx context.Context, in *Void, opts ...grpc.CallOption) (Jobs_GetAllServicesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Jobs_serviceDesc.Streams[0], "/api.Jobs/GetAllServices", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobsGetAllServicesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Jobs_GetAllServicesClient interface {
	Recv() (*Service, error)
	grpc.ClientStream
}

type jobsGetAllServicesClient struct {
	grpc.ClientStream
}

func (x *jobsGetAllServicesClient) Recv() (*Service, error) {
	m := new(Service)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jobsClient) GetAllSkillCategories(ctx context.Context, in *Skill, opts ...grpc.CallOption) (Jobs_GetAllSkillCategoriesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Jobs_serviceDesc.Streams[1], "/api.Jobs/GetAllSkillCategories", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobsGetAllSkillCategoriesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Jobs_GetAllSkillCategoriesClient interface {
	Recv() (*SkillCategory, error)
	grpc.ClientStream
}

type jobsGetAllSkillCategoriesClient struct {
	grpc.ClientStream
}

func (x *jobsGetAllSkillCategoriesClient) Recv() (*SkillCategory, error) {
	m := new(SkillCategory)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jobsClient) GetAllSkills(ctx context.Context, in *SkillCategory, opts ...grpc.CallOption) (Jobs_GetAllSkillsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Jobs_serviceDesc.Streams[2], "/api.Jobs/GetAllSkills", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobsGetAllSkillsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Jobs_GetAllSkillsClient interface {
	Recv() (*Skill, error)
	grpc.ClientStream
}

type jobsGetAllSkillsClient struct {
	grpc.ClientStream
}

func (x *jobsGetAllSkillsClient) Recv() (*Skill, error) {
	m := new(Skill)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jobsClient) PostJob(ctx context.Context, in *CreateJob, opts ...grpc.CallOption) (*Job, error) {
	out := new(Job)
	err := c.cc.Invoke(ctx, "/api.Jobs/PostJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsClient) GetJobs(ctx context.Context, in *ID, opts ...grpc.CallOption) (Jobs_GetJobsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Jobs_serviceDesc.Streams[3], "/api.Jobs/GetJobs", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobsGetJobsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Jobs_GetJobsClient interface {
	Recv() (*Job, error)
	grpc.ClientStream
}

type jobsGetJobsClient struct {
	grpc.ClientStream
}

func (x *jobsGetJobsClient) Recv() (*Job, error) {
	m := new(Job)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jobsClient) ApplyForJob(ctx context.Context, in *JobApplication, opts ...grpc.CallOption) (*ErrorCode, error) {
	out := new(ErrorCode)
	err := c.cc.Invoke(ctx, "/api.Jobs/ApplyForJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsClient) GetApplicants(ctx context.Context, in *ID, opts ...grpc.CallOption) (Jobs_GetApplicantsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Jobs_serviceDesc.Streams[4], "/api.Jobs/GetApplicants", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobsGetApplicantsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Jobs_GetApplicantsClient interface {
	Recv() (*FreelancerProfile, error)
	grpc.ClientStream
}

type jobsGetApplicantsClient struct {
	grpc.ClientStream
}

func (x *jobsGetApplicantsClient) Recv() (*FreelancerProfile, error) {
	m := new(FreelancerProfile)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jobsClient) SelectForJob(ctx context.Context, in *JobSelection, opts ...grpc.CallOption) (*ErrorCode, error) {
	out := new(ErrorCode)
	err := c.cc.Invoke(ctx, "/api.Jobs/SelectForJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsClient) GetAcceptedFreelancers(ctx context.Context, in *ID, opts ...grpc.CallOption) (Jobs_GetAcceptedFreelancersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Jobs_serviceDesc.Streams[5], "/api.Jobs/GetAcceptedFreelancers", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobsGetAcceptedFreelancersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Jobs_GetAcceptedFreelancersClient interface {
	Recv() (*FreelancerProfile, error)
	grpc.ClientStream
}

type jobsGetAcceptedFreelancersClient struct {
	grpc.ClientStream
}

func (x *jobsGetAcceptedFreelancersClient) Recv() (*FreelancerProfile, error) {
	m := new(FreelancerProfile)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jobsClient) GetAcceptedJobs(ctx context.Context, in *ID, opts ...grpc.CallOption) (Jobs_GetAcceptedJobsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Jobs_serviceDesc.Streams[6], "/api.Jobs/GetAcceptedJobs", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobsGetAcceptedJobsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Jobs_GetAcceptedJobsClient interface {
	Recv() (*Job, error)
	grpc.ClientStream
}

type jobsGetAcceptedJobsClient struct {
	grpc.ClientStream
}

func (x *jobsGetAcceptedJobsClient) Recv() (*Job, error) {
	m := new(Job)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jobsClient) GetHistoryJobs(ctx context.Context, in *ID, opts ...grpc.CallOption) (Jobs_GetHistoryJobsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Jobs_serviceDesc.Streams[7], "/api.Jobs/GetHistoryJobs", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobsGetHistoryJobsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Jobs_GetHistoryJobsClient interface {
	Recv() (*Job, error)
	grpc.ClientStream
}

type jobsGetHistoryJobsClient struct {
	grpc.ClientStream
}

func (x *jobsGetHistoryJobsClient) Recv() (*Job, error) {
	m := new(Job)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jobsClient) FinishJob(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ErrorCode, error) {
	out := new(ErrorCode)
	err := c.cc.Invoke(ctx, "/api.Jobs/FinishJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobsServer is the server API for Jobs service.
type JobsServer interface {
	GetAllServices(*Void, Jobs_GetAllServicesServer) error
	GetAllSkillCategories(*Skill, Jobs_GetAllSkillCategoriesServer) error
	GetAllSkills(*SkillCategory, Jobs_GetAllSkillsServer) error
	PostJob(context.Context, *CreateJob) (*Job, error)
	GetJobs(*ID, Jobs_GetJobsServer) error
	ApplyForJob(context.Context, *JobApplication) (*ErrorCode, error)
	GetApplicants(*ID, Jobs_GetApplicantsServer) error
	SelectForJob(context.Context, *JobSelection) (*ErrorCode, error)
	GetAcceptedFreelancers(*ID, Jobs_GetAcceptedFreelancersServer) error
	GetAcceptedJobs(*ID, Jobs_GetAcceptedJobsServer) error
	GetHistoryJobs(*ID, Jobs_GetHistoryJobsServer) error
	FinishJob(context.Context, *ID) (*ErrorCode, error)
}

// UnimplementedJobsServer can be embedded to have forward compatible implementations.
type UnimplementedJobsServer struct {
}

func (*UnimplementedJobsServer) GetAllServices(req *Void, srv Jobs_GetAllServicesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllServices not implemented")
}
func (*UnimplementedJobsServer) GetAllSkillCategories(req *Skill, srv Jobs_GetAllSkillCategoriesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllSkillCategories not implemented")
}
func (*UnimplementedJobsServer) GetAllSkills(req *SkillCategory, srv Jobs_GetAllSkillsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllSkills not implemented")
}
func (*UnimplementedJobsServer) PostJob(ctx context.Context, req *CreateJob) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostJob not implemented")
}
func (*UnimplementedJobsServer) GetJobs(req *ID, srv Jobs_GetJobsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetJobs not implemented")
}
func (*UnimplementedJobsServer) ApplyForJob(ctx context.Context, req *JobApplication) (*ErrorCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyForJob not implemented")
}
func (*UnimplementedJobsServer) GetApplicants(req *ID, srv Jobs_GetApplicantsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetApplicants not implemented")
}
func (*UnimplementedJobsServer) SelectForJob(ctx context.Context, req *JobSelection) (*ErrorCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectForJob not implemented")
}
func (*UnimplementedJobsServer) GetAcceptedFreelancers(req *ID, srv Jobs_GetAcceptedFreelancersServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAcceptedFreelancers not implemented")
}
func (*UnimplementedJobsServer) GetAcceptedJobs(req *ID, srv Jobs_GetAcceptedJobsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAcceptedJobs not implemented")
}
func (*UnimplementedJobsServer) GetHistoryJobs(req *ID, srv Jobs_GetHistoryJobsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetHistoryJobs not implemented")
}
func (*UnimplementedJobsServer) FinishJob(ctx context.Context, req *ID) (*ErrorCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishJob not implemented")
}

func RegisterJobsServer(s *grpc.Server, srv JobsServer) {
	s.RegisterService(&_Jobs_serviceDesc, srv)
}

func _Jobs_GetAllServices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Void)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobsServer).GetAllServices(m, &jobsGetAllServicesServer{stream})
}

type Jobs_GetAllServicesServer interface {
	Send(*Service) error
	grpc.ServerStream
}

type jobsGetAllServicesServer struct {
	grpc.ServerStream
}

func (x *jobsGetAllServicesServer) Send(m *Service) error {
	return x.ServerStream.SendMsg(m)
}

func _Jobs_GetAllSkillCategories_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Skill)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobsServer).GetAllSkillCategories(m, &jobsGetAllSkillCategoriesServer{stream})
}

type Jobs_GetAllSkillCategoriesServer interface {
	Send(*SkillCategory) error
	grpc.ServerStream
}

type jobsGetAllSkillCategoriesServer struct {
	grpc.ServerStream
}

func (x *jobsGetAllSkillCategoriesServer) Send(m *SkillCategory) error {
	return x.ServerStream.SendMsg(m)
}

func _Jobs_GetAllSkills_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SkillCategory)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobsServer).GetAllSkills(m, &jobsGetAllSkillsServer{stream})
}

type Jobs_GetAllSkillsServer interface {
	Send(*Skill) error
	grpc.ServerStream
}

type jobsGetAllSkillsServer struct {
	grpc.ServerStream
}

func (x *jobsGetAllSkillsServer) Send(m *Skill) error {
	return x.ServerStream.SendMsg(m)
}

func _Jobs_PostJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServer).PostJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Jobs/PostJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServer).PostJob(ctx, req.(*CreateJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jobs_GetJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobsServer).GetJobs(m, &jobsGetJobsServer{stream})
}

type Jobs_GetJobsServer interface {
	Send(*Job) error
	grpc.ServerStream
}

type jobsGetJobsServer struct {
	grpc.ServerStream
}

func (x *jobsGetJobsServer) Send(m *Job) error {
	return x.ServerStream.SendMsg(m)
}

func _Jobs_ApplyForJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobApplication)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServer).ApplyForJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Jobs/ApplyForJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServer).ApplyForJob(ctx, req.(*JobApplication))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jobs_GetApplicants_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobsServer).GetApplicants(m, &jobsGetApplicantsServer{stream})
}

type Jobs_GetApplicantsServer interface {
	Send(*FreelancerProfile) error
	grpc.ServerStream
}

type jobsGetApplicantsServer struct {
	grpc.ServerStream
}

func (x *jobsGetApplicantsServer) Send(m *FreelancerProfile) error {
	return x.ServerStream.SendMsg(m)
}

func _Jobs_SelectForJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobSelection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServer).SelectForJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Jobs/SelectForJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServer).SelectForJob(ctx, req.(*JobSelection))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jobs_GetAcceptedFreelancers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobsServer).GetAcceptedFreelancers(m, &jobsGetAcceptedFreelancersServer{stream})
}

type Jobs_GetAcceptedFreelancersServer interface {
	Send(*FreelancerProfile) error
	grpc.ServerStream
}

type jobsGetAcceptedFreelancersServer struct {
	grpc.ServerStream
}

func (x *jobsGetAcceptedFreelancersServer) Send(m *FreelancerProfile) error {
	return x.ServerStream.SendMsg(m)
}

func _Jobs_GetAcceptedJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobsServer).GetAcceptedJobs(m, &jobsGetAcceptedJobsServer{stream})
}

type Jobs_GetAcceptedJobsServer interface {
	Send(*Job) error
	grpc.ServerStream
}

type jobsGetAcceptedJobsServer struct {
	grpc.ServerStream
}

func (x *jobsGetAcceptedJobsServer) Send(m *Job) error {
	return x.ServerStream.SendMsg(m)
}

func _Jobs_GetHistoryJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobsServer).GetHistoryJobs(m, &jobsGetHistoryJobsServer{stream})
}

type Jobs_GetHistoryJobsServer interface {
	Send(*Job) error
	grpc.ServerStream
}

type jobsGetHistoryJobsServer struct {
	grpc.ServerStream
}

func (x *jobsGetHistoryJobsServer) Send(m *Job) error {
	return x.ServerStream.SendMsg(m)
}

func _Jobs_FinishJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServer).FinishJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Jobs/FinishJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServer).FinishJob(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Jobs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Jobs",
	HandlerType: (*JobsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostJob",
			Handler:    _Jobs_PostJob_Handler,
		},
		{
			MethodName: "ApplyForJob",
			Handler:    _Jobs_ApplyForJob_Handler,
		},
		{
			MethodName: "SelectForJob",
			Handler:    _Jobs_SelectForJob_Handler,
		},
		{
			MethodName: "FinishJob",
			Handler:    _Jobs_FinishJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllServices",
			Handler:       _Jobs_GetAllServices_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllSkillCategories",
			Handler:       _Jobs_GetAllSkillCategories_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllSkills",
			Handler:       _Jobs_GetAllSkills_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetJobs",
			Handler:       _Jobs_GetJobs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetApplicants",
			Handler:       _Jobs_GetApplicants_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAcceptedFreelancers",
			Handler:       _Jobs_GetAcceptedFreelancers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAcceptedJobs",
			Handler:       _Jobs_GetAcceptedJobs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetHistoryJobs",
			Handler:       _Jobs_GetHistoryJobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
